# -*- coding:utf-8 -*-
from  . import  pacientes_hc
from  . import  religiones
from  . import  grupos_sanguineos
from  . import  orientacion_sexual
from  . import  identidad_genero
from  . import  estados_civiles
from  . import  antecedente_trabajo
from  . import  instrucciones_names
from  . import  profesion_names
from  . import  puestos_names
from  . import  areas_trabajos
from  . import  ocupaciones_names