# -*- coding:utf-8 -*-
from  . import  inicio_1_
from  . import  inicio_2
from  . import  inicio_2_riegos
from  . import  inicio_2_riesgos_detail
from  . import  tipos_riesgos
from  . import  inicio_2_riesgos_2
from  . import  organos_sistemas
from  . import  organos_sistemas_
from  . import  inicio_3
from  . import  regiones_examen
from . import  regiones_types
from . import  subregiones_types
from  . import  columnas_extremidades
from . import  signos_clinicos
from  . import  resultado_examenes
from  . import  examen_types
from  . import  motivo_diagnostico
from  . import  motivos_diagnosticos
from  . import  actitud_medica
from . import  recomendaciones_tratamientos
from  . import  certificado
from  . import  certificado_evaluacion
from  . import  evaluacion_medica
from  . import  periodica_1
from  . import  motivo_consulta
from  . import  periodica_1_habitos
from  . import  cie_10
from  . import  profesionales_doctores
from  . import  reintengro_form
from  . import  actividades_laborales
from  . import  retiro_1_form
from  . import  factores_riesgos
from  . import  factores_riegos_types
from  . import  retiro_2
from  . import  registro_inmunizaciones
from  . import  vacunas_names
from  . import  inmunizaciones_ids