# -*- coding:utf-8 -*-
{
    "name": "Formularios Médicos",
    "version": "1.0",
    "author": "Randy Ciprian",
    "category": "Healthcare",
    "summary": "Módulo para gestión de formularios médicos y registros de pacientes",
    "description": """
        Este módulo permite gestionar formularios médicos personalizados,
        almacenar datos de pacientes y facilitar el seguimiento clínico.
    """,
    "depends": ["base", "mail",'HC_PACIENTES', 'HC_INSTITUCIONES'],
    "data": [
        'data/data.xml',
        'report/report_inicio_1_.xml',
        'report/report_inicio_2.xml',
        'report/report_inicio_3.xml',
        'report/certificado_report.xml',
        'report/periodica_1_report.xml',
        'report/report_reintegro.xml',
        'report/report_retiro_1_.xml',
        'report/report_retiro_2.xml',
        'report/report_inmunizaciones.xml',
        'report/report.xml',
        'views/form_view_inicio1.xml',
        'views/tree_view_inicio1.xml',
        'views/form_01_action.xml',
        'views/form_view_inicio2.xml',
        'views/form_02_action.xml',
        'views/form_view_inicio3.xml',
        'views/form_03_action.xml',
        'views/certificado_form_view.xml',
        'views/certificado_action.xml',
        'views/view_periodica.xml',
        'views/periodica_1_action.xml',
        'views/reintegro_form.xml',
        'views/action_reintegro.xml',
        'views/retiro_1_form.xml',
        'views/action_retiro_1.xml',
        'views/retiro_2_form_view.xml',
        'views/retiro_2_action.xml',
        'views/registro_inmunizaciones.xml',
        'views/action_inmunizaciones.xml',
        'views/menu.xml',
        'security/ir.model.access.csv',

    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
